language: ruby
dist: xenial
addons:
  apt:
    packages:
    - graphviz
env:
- SLIDES_DIR=slides PDF_NAME=template

install:
- gem install
    asciidoctor
    asciidoctor-diagram
    asciimath
    pango
    asciidoctor-mathematical
    asciidoctor-revealjs
    pygments.rb
- gem install asciidoctor-pdf --pre

script:
- asciidoctor-revealjs --destination-dir "$SLIDES_DIR" index.adoc
- asciidoctor-pdf
  --require asciidoctor-mathematical --attribute mathematical-format=svg
  --out-file "${SLIDES_DIR}/${PDF_NAME}.pdf" index.adoc

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  committer_from_gh: true
  skip_cleanup: true
  keep_history: true
  local_dir: $SLIDES_DIR
  on:
    branch: master
