language: ruby
dist: xenial
addons:
  apt:
    packages:
    - graphviz

env:
  global:
  - SLIDES_DIR=slides PDF_NAME=template

install:
- gem install
    pango
    rouge
    asciidoctor
    asciidoctor-diagram
    asciidoctor-mathematical
    asciidoctor-revealjs
    asciimath
- gem install asciidoctor-pdf --pre
- git clone https://github.com/hakimel/reveal.js.git "$SLIDES_DIR/reveal.js"
- pushd "$SLIDES_DIR/reveal.js" && npm install && popd

script:
- asciidoctor-revealjs --destination-dir "$SLIDES_DIR" index.adoc
- asciidoctor-pdf
    --require asciidoctor-mathematical --attribute mathematical-format=svg
    --out-file "${SLIDES_DIR}/${PDF_NAME}.pdf" index.adoc

deploy:
  provider: pages
  github_token: "$GITHUB_TOKEN"
  committer_from_gh: true
  skip_cleanup: true
  keep_history: true
  local_dir: "$SLIDES_DIR"
  on:
    branch: master

notifications:
  slack:
    rooms:
    - "$SLACK_TOKEN"
    template:
    - "Build <%{build_url}|#%{build_number}> *%{result}* in %{duration}"
    - "Repo: <https://github.com/%{repository_slug}|%{repository_slug}>@<https://github.com/%{repository_slug}/tree/%{branch}|%{branch}>"
    - "Commit: <%{compare_url}|%{commit}> (%{commit_subject}) by _%{author}_"
    on_start: never
    on_success: always
    on_failure: always
