language: ruby
dist: xenial
addons:
  apt:
    packages:
    - graphviz
env:
- SLIDES_DIR=slides PDF_NAME=template

install:
- gem install asciidoctor
- gem install asciidoctor-diagram
- gem install asciidoctor-mathematical
- gem install asciimath
- gem install asciidoctor-revealjs
- gem install asciidoctor-pdf

script:
- asciidoctor-revealjs --destination-dir "$SLIDES_DIR" index.adoc
- asciidoctor-pdf --out-file "${SLIDES_DIR}/${PDF_NAME}.pdf" index.adoc

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  committer_from_gh: true
  skip_cleanup: true
  keep_history: true
  local_dir: $SLIDES_DIR
  on:
    branch: master
