language: ruby
dist: xenial
addons:
  apt:
    packages:
    - graphviz
env:
- SLIDES_DIR=slides PDF_NAME=template

install:
- gem install
    pango
    prawn-gmagick
    rouge
    asciidoctor
    asciidoctor-diagram
    asciidoctor-mathematical
    asciidoctor-revealjs
    asciimath
- gem install asciidoctor-pdf --pre

script:
- asciidoctor-revealjs
    --attribute revealjsdir=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0/
    --destination-dir "$SLIDES_DIR" index.adoc
- asciidoctor-pdf
    --require asciidoctor-mathematical --attribute mathematical-format=svg
    --out-file "${SLIDES_DIR}/${PDF_NAME}.pdf" index.adoc

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  committer_from_gh: true
  skip_cleanup: true
  keep_history: true
  local_dir: $SLIDES_DIR
  on:
    branch: master

notifications:
  webhooks:
    urls:
    - $GITTER_WEBHOOK
    on_success: change
    on_failure: always
    on_start: never